default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: python Tools/CodeQuality/clang_format_hook.py
        language: system
        files: \.(c|cc|cpp|cxx|h|hpp|m|mm)$
        stages:
          - pre-commit

      - id: clang-format-check
        name: clang-format-check
        entry: python Tools/CodeQuality/clang_format_hook.py --check --all-files
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-push
